### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by olifre** [BGO-OD/OptionParser#2]
We now have automatic compilation with mingw64 and mingw32 in an MSYS2 system in a Windows VM (using the free appveyor service). 
However, we don't compile - we need replacements for basename(), e.g.:
http://permalink.gmane.org/gmane.comp.gnu.mingw.devel/1268
and readlink().

**Comment by JHannappel** [comment]
fixed since 
https://github.com/BGO-OD/OptionParser/commit/98c4ded29084fd1720b246a2e79fa7d769dad039

The things that won't work on windows are not done there
