### ISSUE TITLE
Pre / post text in help output

### ISSUE THREAD

**Issue by olifre** [BGO-OD/OptionParser#4]
It would be cool to be able to add some pre- and post-text in the help output. 
It could include things like the program's version, a minimal description on what it's good for, necessary warnings (never do xy) and so on. 
Should be auto-wrapping and prevent that any lines start with "-" so we stay parseable.

**Comment by JHannappel** [comment]
is already in, the prefix text is the aDescription parameter of the OptionParser contructor and the post-text is the aTrailer parameter.
